# Generated by Django 4.2.6 on 2023-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ImageField(upload_to='Carrusel', verbose_name='Imagen')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image_title', models.ImageField(null=True, upload_to='Carrusel', verbose_name='Imagen de titulo')),
                ('width', models.CharField(max_length=20, verbose_name='Ancho')),
                ('height', models.CharField(max_length=20, verbose_name='Alto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imagenes del carrusel',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=200, verbose_name='Número de teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.BooleanField(default=False, verbose_name='Contestado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='how',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Que hace',
                'verbose_name_plural': 'Que hace',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='what',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Que es',
                'verbose_name_plural': 'Que es',
                'ordering': ['-created'],
            },
        ),
    ]
