# Generated by Django 4.2.6 on 2023-11-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusellanding',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Texto'),
        ),
    ]
