# Generated by Django 4.2.6 on 2023-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carusellanding_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusellanding',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto'),
        ),
    ]
