# Generated by Django 4.2.6 on 2023-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carusellanding_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='Logo', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='Logo', verbose_name='Imagen')),
                ('information', models.TextField(verbose_name='Información')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyecto',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='how',
            name='name',
        ),
        migrations.RemoveField(
            model_name='what',
            name='name',
        ),
        migrations.AddField(
            model_name='how',
            name='text',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='how',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='what',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Mensaje'),
        ),
    ]
